[site]
title = "Sen Mei"
description = "Algorithm Engineer at Qiyuan Lab."
last_updated = "December 7, 2025"

[author]
name = "Sen Mei"
title = "Algorithm Engineer"
institution = "Qiyuan Lab"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "meisen2025@gmail.com"
location = "Beijing, China"
location_url = "https://maps.google.com/?q=Beijing+China"
location_details = [
  "Tsinghua University, Beijing, China"
]
google_scholar = "https://scholar.google.com/citations?hl=en&user=JWqmlrcAAAAJ"
github = "https://github.com/mssssss123"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"


